blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/laravelcm/jobs-portail-issues/issues/new
    about: Submit a bug or an issue
  - name: Feature request
    url: https://github.com/shopperlabs/jobs-portail-issues/discussions/new
    about: For ideas or feature requests